### ISSUE TITLE
epoch table does not populate current epoch

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-db-sync#139] opened 2020-06-17 15:12 UTC
This shows most recent block (epoch 50) doesn't have an epoch listed in epoch table. This breaks the functionality of the frontend explorer on shelley environments.

```
cexplorer=# SELECT tx_count,blk_count,no FROM epoch ORDER BY no DESC LIMIT 1;
 tx_count | blk_count | no 
----------+-----------+----
      315 |       810 | 49
(1 row)

cexplorer=# SELECT id,hash,epoch_no,slot_no,block_no FROM block WHERE id=44145;
  id   |                                hash                                | epoch_no | slot_no | block_no 
-------+--------------------------------------------------------------------+----------+---------+----------
 44145 | \x661b5facbacca4897b8679fbefd7c4219d06d3b4e34b368adac2e65a69281790 |       50 | 1087736 |    44135
(1 row)
```

**Comment by erikd** [comment] 2020-06-18 00:38
99.9% sure this is a duplicate of https://github.com/input-output-hk/cardano-db-sync/issues/111 .

**Comment by disassembler** [comment] 2020-06-18 15:51
I'm not sure it is, as #111 happens at the epoch boundary, somewhat nondeterministically. This one always trails 1 behind in the epoch table.

**Comment by disassembler** [comment] 2020-06-18 16:13
I manually inserted a dummy row which unbreaks the explorer frontend:

```
 INSERT INTO epoch (out_sum,tx_count, blk_count,no,start_time,end_time) VALUES (0, 0, 0, 54, NOW(), NOW());
```

But then the epoch just shows those dummy values. Contrasted to byron, where that row is updated on every block inserted to increase the counters. I think this is likely a shelley specific bug where the epoch table isn't handled receiving new blocks. It appears instead it populates the epoch at the end of the epoch.

**Comment by disassembler** [comment] 2020-06-19 02:50
Here's logs of what happens at new epoch. The logs show it inserts row for the end of the epoch (55), and the it starts continuing on epoch 56, but doesn't populate epoch table row with new epoch.

**Closed** 2020-07-02 15:21 UTC
