### ISSUE TITLE
 db-sync deletes all already synced data after restart

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-db-sync#504] opened 2021-01-25 00:30 UTC
I ran into an issue where after stopping `db-sync` with `Ctrl+C` and starting it again I can see that it deletes all synced data:

```
[db-sync-node:Info:46] [2021-01-25 00:15:03.58 UTC] Starting chainSyncClient
[db-sync-node:Info:46] [2021-01-25 00:15:03.60 UTC] Database tip is at slot 300997, block 299696
[db-sync-node:Info:50] [2021-01-25 00:15:03.60 UTC] Running DB thread
[db-sync-node.Subscription:Notice:41] [2021-01-25 00:15:03.60 UTC] Identity Required subscriptions started
[db-sync-node:Info:50] [2021-01-25 00:15:03.68 UTC] Rolling back to slot 0, hash 5083d7d6e3463acd1fe3d3fc76151c2a0fa4b9e43e473a37aac1db0ad1826cd6
[db-sync-node:Info:53] [2021-01-25 00:15:03.70 UTC] getHistoryInterpreter: acquired
[db-sync-node:Info:50] [2021-01-25 00:15:04.63 UTC] Deleting slots numbered: [300997..1]
```

In above example it had already synced 12 epochs (this was on `stage`). 
For fully synced `shelley-qa` it also deleted [current_max.. 1].

cardano node version: 1.25.0 → commit 9d62ffad185eafaabc35682355602fb5b61d33f6
db-sync version: 8.0.0 →  commit 3ef5127bfc7c6df0e56b61f51c665a6195d1b31d  from release/8.0.x

**Comment by erikd** [comment] 2021-01-25 00:35
Duplicate of https://github.com/input-output-hk/cardano-db-sync/pull/503

**Closed by erikd** 2021-01-25 00:35 UTC
