### ISSUE TITLE
Sanchonet: SNErrDefault: insertDelegation "SNErrDefault"

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/cardano-db-sync#1540] opened 2023-10-21 09:16 UTC
**OS**
Your OS: NixOS

**Versions**
The `db-sync` version:  branch `sancho-2-0-0` at `d2227a15d95a3bd24ee3b4aff6e25085091b279f`

`cardano-db-sync` crashes at the block `82627f94b48cbff1365c764ca28a3deea76371784cac542bd50b93d7b09586e5` with error `Error SNErrDefault: "insertDelegation \"PoolKeyHash\"`.

```
Oct 21 06:58:19 dbsync1 cardano[1770]: Chain extended, new tip: 82627f94b48cbff1365c764ca28a3deea76371784cac542bd50b93d7b09586e5 at slot 11082499
Oct 21 06:58:19 dbsync1 74dagnr1wxbh4rz9slj00lm2vwdzyq8b-cardano-db-sync[888]: [db-sync-node:Error:57] [2023-10-21 06:58:19.32 UTC] Error SNErrDefault: "insertDelegation \"PoolKeyHash\""
Oct 21 06:58:19 dbsync1 74dagnr1wxbh4rz9slj00lm2vwdzyq8b-cardano-db-sync[888]: [db-sync-node:Info:57] [2023-10-21 06:58:19.32 UTC] Shutting down DB thread
Oct 21 06:58:22 dbsync1 cardano[1770]: Chain extended, new tip: 47e4a293de8a7230b356cf1924e900d2c13b6279faf9b9a983bf9b72e767915a at slot 11082502
```

**Comment by mmahut** [comment] 2023-10-21 11:41
Interesting enough, after few restarts this error has been ignored and the sync did continue as usual.

**Comment by johnalotoski** [comment] 2023-10-21 14:52
We hit the same issue, same log message, and like @mmahut, restarting cardano-db-sync twice had dbsync resumed like normal on sanchonet.

**Comment by kderme** [comment] 2023-10-22 09:17
The issue happens two times, due to `ConwayRegDelegCert` certificates, delegating to unregistered pools `dd0ea164d7d0bcef21ee22b70046addefff486c2f95333209db55635` and `e998b0997243c292581664c370d2fdf86abdbd0a05f7e559b4ec0d61` at blocks `82627f94b48cbff1365c764ca28a3deea76371784cac542bd50b93d7b09586e5` and `46214a44bc99eee97959073b8f72904c53c1b29bb1b83fa919b82678e19f0ee0` resperctively.

There is an inconsistency in how delegations are handled by the ledger. For normal delegations, the pool target needs to be a registered pool, while for `ConwayRegDelegCert` it's not necessary to be registered. DBSync assumes it's reegistered for all certificates.

Imo until this is fixed in ledger we can create a tag which ignores these certificates which shouldn't be on chain anyway.

**Comment by kderme** [comment] 2023-10-22 11:05
It seems there was another crash related to stake distribution, caused by this unregistered pool living in ledger.

```
[db-sync-node:Error:58] [2023-10-22 10:30:14.62 UTC] Error SNErrDefault: "insertEpochStake.queryPoolKeyWithCache \"PoolKeyHash\""
```

I think this gives an adequete workaround https://github.com/input-output-hk/cardano-db-sync/pull/1542

**Comment by kderme** [comment] 2023-10-22 14:35
Tag `sancho-2-0-1` is created with the workaround. I think we can close this.

**Closed** 2023-10-23 13:16 UTC
Labels: bug, conway
