### ISSUE TITLE
Failed to parse ledger state file: too many bytes

### ISSUE THREAD

**Issue by Fell-x27** [input-output-hk/cardano-db-sync#1206] opened 2022-07-22 14:53 UTC
**OS**
Your OS: Linux Mint 20

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0.0
PostgreSQL version: 12.11

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: hydra binaries

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): terminal command with flags

**Additional context**
The database was restored from a snapshot. Then it was up-synced to actual state. Then db-sync was shut down with the ctrl+c command as usual. Then started again after a couple hours. 

**Problem Report**
[db-sync-node:Info:66] [2022-07-22 12:43:57.97 UTC] Cardano.Db tip is at slot 64108486, block 3726321
[db-sync-node:Info:75] [2022-07-22 12:43:57.97 UTC] Running Offline fetch thread
[db-sync-node:Info:74] [2022-07-22 12:43:57.98 UTC] Running DB thread
[db-sync-node:Info:74] [2022-07-22 12:43:57.99 UTC] Rolling back to slot 64097321, hash 2a18313627b979ea1828d1c2ab108545f09eddaf54a45ef000ec68777d492334
[db-sync-node:Info:74] [2022-07-22 12:43:58.01 UTC] Deleting 322 blocks up to slot 64108486
[db-sync-node:Info:74] [2022-07-22 12:44:01.99 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:44:22.98 UTC] Failed to parse ledger state file ../db_sync_storage/64097321-2a18313627.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 36770724 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:44:23.32 UTC] Rolling back further to slot 64079796
[db-sync-node:Info:74] [2022-07-22 12:44:23.46 UTC] Rolling back to slot 64079796, hash 75ff0dcca1fddca832668e93c0a9e3abd96641a90143605bd8edbac2de10c6c4
[db-sync-node:Info:74] [2022-07-22 12:44:23.57 UTC] Deleting 500 blocks up to slot 64097321
[db-sync-node:Info:74] [2022-07-22 12:44:27.73 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:44:48.81 UTC] Failed to parse ledger state file ../db_sync_storage/64079796-75ff0dcca1.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 36666208 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:44:49.00 UTC] Rolling back further to slot 63881170
[db-sync-node:Info:74] [2022-07-22 12:44:49.12 UTC] Rolling back to slot 63881170, hash 3a0c1a7115b18df33b935dbeebefa307b5ab64f2b7467dad7fe33150dfd35ced
[db-sync-node:Info:74] [2022-07-22 12:44:49.47 UTC] Deleting 5500 blocks up to slot 64079796
[db-sync-node:Info:74] [2022-07-22 12:45:27.24 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:45:44.68 UTC] Failed to parse ledger state file ../db_sync_storage/63881170-3a0c1a7115.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 35852658 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:45:44.80 UTC] Rolling back further to slot 63806395
[db-sync-node:Info:74] [2022-07-22 12:45:45.06 UTC] Rolling back to slot 63806395, hash 1a90a5ca953dca1a30615b157e16e38dfe04cc0975783bd3f5f039170d3eb2ac
[db-sync-node:Info:74] [2022-07-22 12:45:45.15 UTC] Deleting 2165 blocks up to slot 63881170
[db-sync-node:Info:74] [2022-07-22 12:45:59.22 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:46:14.11 UTC] Failed to parse ledger state file ../db_sync_storage/63806395-1a90a5ca95-217.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 35617589 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:46:14.25 UTC] Rolling back further to slot 63529543
[db-sync-node:Info:74] [2022-07-22 12:46:14.30 UTC] Rolling back to slot 63529543, hash bdb2c218c0ecf42107f23382c6dba94f092049756ab4fe26cce823d8d3a140f8
[db-sync-node:Info:74] [2022-07-22 12:46:14.70 UTC] Deleting 7835 blocks up to slot 63806395
[db-sync-node:Info:74] [2022-07-22 12:47:03.92 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:47:17.30 UTC] Failed to parse ledger state file ../db_sync_storage/63529543-bdb2c218c0.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 34683004 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:47:17.40 UTC] Rolling back further to slot 63374399
[db-sync-node:Info:74] [2022-07-22 12:47:17.46 UTC] Rolling back to slot 63374399, hash 6eea1e80cab286c55fbf6109a4f9ced91d105dc64de627308d39284d2b2acbea
[db-sync-node:Info:74] [2022-07-22 12:47:17.70 UTC] Deleting 4318 blocks up to slot 63529543
[db-sync-node:Info:74] [2022-07-22 12:47:44.72 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:47:59.82 UTC] Failed to parse ledger state file ../db_sync_storage/63374399-6eea1e80ca-216.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 34160864 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:47:59.96 UTC] Rolling back further to slot 63174931
[db-sync-node:Info:74] [2022-07-22 12:48:00.47 UTC] Rolling back to slot 63174931, hash 101cde77065304926db2a0e81030884a707e7b1d7509344126579723362a02ec
[db-sync-node:Info:74] [2022-07-22 12:48:00.75 UTC] Deleting 5682 blocks up to slot 63374399
[db-sync-node:Info:74] [2022-07-22 12:48:34.95 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:48:47.96 UTC] Failed to parse ledger state file ../db_sync_storage/63174931-101cde7706.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 33368722 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:48:48.15 UTC] Rolling back further to slot 62942377
[db-sync-node:Info:74] [2022-07-22 12:48:48.32 UTC] Rolling back to slot 62942377, hash 289deaf2f73d0889a8c4ddd112dff7df42ed239d410638bdde98c7327c40207d
[db-sync-node:Info:74] [2022-07-22 12:48:48.70 UTC] Deleting 6680 blocks up to slot 63174931
[db-sync-node:Info:74] [2022-07-22 12:49:14.82 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:49:27.77 UTC] Failed to parse ledger state file ../db_sync_storage/62942377-289deaf2f7-215.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 32483506 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:49:27.85 UTC] Rolling back further to slot 62821228
[db-sync-node:Info:74] [2022-07-22 12:49:27.98 UTC] Rolling back to slot 62821228, hash a37f3c2fc204f1c016c48f498a4a582a495e638aad7bcffab21104450c27afe1
[db-sync-node:Info:74] [2022-07-22 12:49:28.17 UTC] Deleting 3320 blocks up to slot 62942377
[db-sync-node:Info:74] [2022-07-22 12:49:44.48 UTC] Blocks deleted
[db-sync-node:Warning:74] [2022-07-22 12:50:00.78 UTC] Failed to parse ledger state file ../db_sync_storage/62821228-a37f3c2fc2.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 32020604 "Decoding TxIx: too many bytes.")'. Deleting it.
[db-sync-node:Warning:74] [2022-07-22 12:50:00.89 UTC] Rolling back further to slot 62510369
[db-sync-node:Info:74] [2022-07-22 12:50:00.97 UTC] Rolling back to slot 62510369, hash d931221f9bc4cae34de422d9f4281a2b0344e86aac6b31eb54e2ee90f44a09b9
[db-sync-node:Info:74] [2022-07-22 12:50:01.51 UTC] Deleting 9405 blocks up to slot 62821228
[db-sync-node:Info:74] [2022-07-22 12:50:58.86 UTC] Blocks deleted
[db-sync-node:Info:74] [2022-07-22 12:51:56.56 UTC] Found snapshot file for slot 62510369, hash d931221f9bc4cae34de422d9f4281a2b0344e86aac6b31eb54e2ee90f44a09b9. It took 7.78022867s to read from disk and 49.877854626s to parse.
[db-sync-node:Info:74] [2022-07-22 12:51:56.72 UTC] Found snapshot file for slot 62510369, hash d931221f9bc4cae34de422d9f4281a2b0344e86aac6b31eb54e2ee90f44a09b9
[db-sync-node:Info:74] [2022-07-22 12:52:01.98 UTC] File ../db_sync_storage/62510369-d931221f9b-214.lstate exists
[db-sync-node:Info:74] [2022-07-22 12:52:27.26 UTC] Inserted 1 deposit refund rewards
[db-sync-node:Info:74] [2022-07-22 12:52:27.26 UTC] Removing 0 orphaned rewards
[db-sync-node:Info:74] [2022-07-22 12:52:54.72 UTC] Validate Epoch Rewards: total rewards that become spendable in epoch 215 are 81808
[db-sync-node:Info:74] [2022-07-22 12:52:54.72 UTC] Starting at epoch 215
[db-sync-node:Info:74] [2022-07-22 12:53:55.62 UTC] Insert Babbage Block: epoch 215, slot 62510442, block 3680595, hash e1a215a1bbfa2b25857fecf10af52198cae54937550b7c3b1dbb61d50e906cf9

So it just dropped everything that was synced after restoration for some reason.

**Comment by kderme** [comment] 2022-07-22 15:53
This is duplicate of https://github.com/input-output-hk/cardano-db-sync/issues/1181 and https://github.com/input-output-hk/cardano-db-sync/issues/1189 which is fixed in tag `13.0.1`

You could try to use the snapshot from https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/index.html#13/ to sync faster.

**Closed** 2022-07-23 05:25 UTC
Labels: bug
