### ISSUE TITLE
loadLedgerStateAtPoint failed to find required state file

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/cardano-db-sync#581] opened 2021-04-16 17:45 UTC
We have seen an interesting failure, on two version of `cardano-db-sync`, both `8.0.0` (cardano-node `1.25.1`) and `9.0.0` (cardano-node `1.26.1`). Probably related to rollbacks and ledger files.

```
Apr 16 17:01:56 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:01:56.21 UTC] Rolling back to SlotNo 27026109, hash 37cab80174f44c13eee3588ae1f0f95ddc88a860a5266456098d1a7dcc038bee
Apr 16 17:01:56 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:01:56.21 UTC] Deleting slots numbered: [27026220]
Apr 16 17:01:56 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:01:56.23 UTC] Slots deleted
Apr 16 17:02:05 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:02:05.53 UTC] insertShelleyBlock(Mary): epoch 260, slot 27026153, block 5599051, hash 61837e71de402ce9181b73b985a09460219f3be705be67dd6c469441ef11e5b0
Apr 16 17:03:10 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:03:10.96 UTC] insertShelleyBlock(Mary): epoch 260, slot 27026299, block 5599052, hash 69e0c257b941bcdc5d646827394475e89275d01afc1257857a0261c015d52749
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:03:15.19 UTC] Rolling back to SlotNo 27026153, hash 61837e71de402ce9181b73b985a09460219f3be705be67dd6c469441ef11e5b0
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:03:15.19 UTC] Deleting slots numbered: [27026299]
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Info:58] [2021-04-16 17:03:15.21 UTC] Slots deleted
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Error:58] [2021-04-16 17:03:15.21 UTC] runDBThread: FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node:Error:54] [2021-04-16 17:03:15.21 UTC] ChainSyncWithBlocksPtcl: FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node.Mux:Info:51] [2021-04-16 17:03:15.21 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: State: Dead
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node.Mux:Notice:51] [2021-04-16 17:03:15.21 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: Miniprotocol MiniProtocolNum 5 InitiatorDir terminated with exception FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node.Subscription:Error:50] [2021-04-16 17:03:15.21 UTC] Identity Application Exception: LocalAddress "/run/cardano-node/node.socket" FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: [db-sync-node.ErrorPolicy:Error:4] [2021-04-16 17:03:15.21 UTC] IP LocalAddress "/run/cardano-node/node.socket" ErrorPolicyLocalNodeError (ApplicationExceptionTrace (FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}))
Apr 16 17:03:15 dbsync1 csh3pjc2b477c2iv1qfx9ajbf6dqclq9-cardano-db-sync[855]: cardano-db-sync-extended: FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
```

```
-- Logs begin at Wed 2021-04-14 18:49:06 UTC, end at Fri 2021-04-16 17:41:24 UTC. --
Apr 16 17:01:54 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:01:54.89 UTC] Rolling back to slot 27026109, hash 37cab80174f44c13eee3588ae1f0f95ddc88a860a5266456098d1a7dcc038bee
Apr 16 17:01:54 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:01:54.89 UTC] Deleting slots numbered: [27026220]
Apr 16 17:01:54 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:01:54.90 UTC] Slots deleted
Apr 16 17:02:01 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:02:01.07 UTC] insertShelleyBlock(Mary): epoch 260, slot 27026153, block 5599051, hash 61837e71de402ce9181b73b985a09460219f3be705be67dd6c469441ef11e5b0
Apr 16 17:03:10 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:03:10.58 UTC] insertShelleyBlock(Mary): epoch 260, slot 27026299, block 5599052, hash 69e0c257b941bcdc5d646827394475e89275d01afc1257857a0261c015d52749
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:03:13.66 UTC] Rolling back to slot 27026153, hash 61837e71de402ce9181b73b985a09460219f3be705be67dd6c469441ef11e5b0
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:03:13.66 UTC] Deleting slots numbered: [27026299]
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Info:51] [2021-04-16 17:03:13.68 UTC] Slots deleted
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Error:51] [2021-04-16 17:03:13.68 UTC] runDBThread: FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node:Error:47] [2021-04-16 17:03:13.68 UTC] ChainSyncWithBlocksPtcl: FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node.Mux:Info:44] [2021-04-16 17:03:13.68 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: State: Dead
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node.Mux:Notice:44] [2021-04-16 17:03:13.68 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: Miniprotocol MiniProtocolNum 5 InitiatorDir terminated with exception FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node.Subscription:Error:42] [2021-04-16 17:03:13.68 UTC] Identity Application Exception: LocalAddress "/run/cardano-node/node.socket" FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: [db-sync-node.ErrorPolicy:Error:4] [2021-04-16 17:03:13.68 UTC] IP LocalAddress "/run/cardano-node/node.socket" ErrorPolicyLocalNodeError (ApplicationExceptionTrace (FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}))
Apr 16 17:03:13 dbsync2 c0ywd3r3dzql03nx76yqddsyh9hvrkp4-cardano-db-sync[11543]: cardano-db-sync-extended: FatalError {fatalErrorMessage = "loadLedgerStateAtPoint failed to find required state file: /var/lib/csyncdb/27026153-61837e71de.lstate"}
Apr 16 17:03:14 dbsync2 systemd[1]: cardano-db-sync.service: Main process exited, code=exited, status=1/FAILURE
Apr 16 17:03:14 dbsync2 systemd[1]: cardano-db-sync.service: Failed with result 'exit-code'.
Apr 16 17:03:14 dbsync2 systemd[1]: cardano-db-sync.service: Consumed 2d 11h 15min 57.263s CPU time, received 112B IP traffic, sent 216B IP traffic.
```

**Comment by erikd** [comment] 2021-04-19 21:18
This is a duplicate of https://github.com/input-output-hk/cardano-db-sync/issues/563 and https://github.com/input-output-hk/cardano-db-sync/issues/570. It is being worked on in https://github.com/input-output-hk/cardano-db-sync/pull/584 .

**Closed** 2021-04-20 14:02 UTC
