### ISSUE TITLE
Latest master crashes on insertMirReserves

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-db-sync#237] opened 2020-08-05 05:10 UTC
This error happens both on my instance and on Nico's instance

```
[db-sync-node:Info:37] [2020-08-05 04:24:02.78 UTC] insertShelleyBlock: epoch 208, slot 4560000, block 4493870, hash 9c333d7065b4f0b526034da0c5b295d5e3205ccbe23a61591dd22334d7ceaeef
[db-sync-node:Error:37] [2020-08-05 04:24:05.98 UTC] DB lookup fail in insertMirReserves: StakeAddress
[db-sync-node:Info:37] [2020-08-05 04:24:05.98 UTC] Shutting down DB thread
[db-sync-node:Error:40] [2020-08-05 04:24:05.98 UTC] recvMsgRollForward: AsyncCancelled
```

Cardano-node version: `1.18.0`
Cardano-db-sync version: `9ac5586149e40eee8ffdd95b9e3aea799055b3a4`

This may be related to the issue Matthew posted earlier where his DB ends up with one withdrawal where no MIR entry exists.

**Comment by rhyslbw** [comment] 2020-08-05 06:14
Confirmed here too:
```
[db-sync-node:Info:36] [2020-08-05 05:58:42.54 UTC] insertShelleyBlock: epoch 208, slot 4560000, block 4493870, hash 9c333d7065b4f0b526034da0c5b295d5e3205ccbe23a61591dd22334d7ceaeef
[db-sync-node:Error:36] [2020-08-05 05:58:55.76 UTC] DB lookup fail in insertMirReserves: StakeAddress
[db-sync-node:Info:36] [2020-08-05 05:58:55.76 UTC] Shutting down DB thread
[db-sync-node:Error:39] [2020-08-05 05:58:55.76 UTC] recvMsgRollForward: AsyncCancelled
```

**Comment by dcoutts** [comment] 2020-08-05 09:14
@SebastienGllmt Is this on mainnet, testnet or MC4?

Can you clarify that this is not happening with the released version, just the master version?

**Comment by longle255** [comment] 2020-08-05 09:52
I also had this problem on mainnet, with the master version. Released version worked fine.

**Comment by ArturWieczorek** [comment] 2020-08-05 09:58
`db-sync` tag: 3.1.0 commit 7f9959c9a0746d44d331cffcf7abb0ef4f4fb948 works fine with **mainnet** and **MC4**, issue is present on master.

**Comment by erikd** [comment] 2020-08-05 10:40
I just restarted my `db-sync` mainnet instance (commit `9ac5586149e40eee8ffdd95b9e3aea799055b3a4`) with a `--rollback-to-
slot 4550000` argument to force a rollback. It then synced past slot `4560000` and all the way to tip slot `5056360`.

I will drop and recreate the db to see if that triggers it.

**Comment by longle255** [comment] 2020-08-05 16:05
I just did a quick check. The master version `9ac5586149e40eee8ffdd95b9e3aea799055b3a4` has that problem with newly created db. But it works on fully synced DB created by version `3.1.0` (with some schema migrations), even with a `--rollback-to- slot 4550000`. Could be a workaround while waiting for a fix.

**Comment by erikd** [comment] 2020-08-05 20:47
Dropped and recreated it.  Now I am hitting this problem :cry: .

**Comment by mmahut** [comment] 2020-08-06 07:30
Confirmed I'm seeing it too. Interesting, I did try to sync it to 3.1.0 and then switching to master, but still seeing it.

**Comment by SebastienGllmt** [comment] 2020-08-06 18:32
confirmed fix by #238

**Comment by mebassett** [comment] 2020-08-06 18:56
can we leave this open under #238 is merged?  that fix does suggest that there may be issues further upstream.

**Comment by erikd** [comment] 2020-08-06 21:36
#238 fixed the problem, but i think it addresses the symptom and I would like to understand the cause before deciding on a fix.

**Comment by erikd** [comment] 2020-08-09 23:15
The spec doc says:
> **3.3.8    Certificate Precedence and Validity**
> The following rules determine precedence and validity of certificates. In particular, they describe what happens when multiple certificates are issued for a given stake pool key.The ordering of blocks and transactions induces a canonical ordering amongst certificates.Thus, the terms older/newer certificate are well defined and are used below.

This actually says nothing about the ordering of MIR certificates with respect to Stake Address registrations.

**Closed** 2020-08-10 02:39 UTC
Labels: bug
