### ISSUE TITLE
Additional indexes speed up deleting blocks

### ISSUE THREAD

**Issue by memewhale** [input-output-hk/cardano-db-sync#975] opened 2021-12-02 08:40 UTC
**OS**
Your OS: Linux 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): cardano-db-sync 11.0.2 - linux-x86_64 - ghc-8.10
PostgreSQL version: 12+214ubuntu0.1

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
cabal install cardano-db-sync

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):
command line (systemd)

**Additional context**

**Problem Report**
Please do not include screenshots or images, but instead cut and paste any relevant log messages
or errors.

db-sync was stuck for many many hours here:
```
[db-sync-node:Info:772642] [2021-12-01 20:16:54.84 UTC] Rolling back to slot 46396728, hash 0b4e19943029e10894330f9988d25d1104b4503cd41a9f623992cd410fbeb4bc
[db-sync-node:Info:772642] [2021-12-01 20:16:54.90 UTC] Deleting 20768 blocks up to slot 46823508
```

```
=> SELECT pid, age(clock_timestamp(), query_start), usename, query FROM pg_stat_activity  WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%' ORDER BY query_start desc;

   pid   |       age       | usename  |                  query                  
---------+-----------------+----------+-----------------------------------------
 2737934 | 03:21:47.472175 | cardano  | DELETE FROM "block" WHERE "id"=6578171 
```

I tried different things (including canceling the DELETE query) but it would always take several hours again without progress. Eventually I found that adding additional foreign key indexes only took a few minutes and the `DELETE` query went through immediately

```
/* From https://www.cybertec-postgresql.com/en/index-your-foreign-key/ */
SELECT c.conrelid::regclass AS "table",
       /* list of key column names in order */
       a.attname as column,
       pg_catalog.pg_size_pretty(
          pg_catalog.pg_relation_size(c.conrelid)
       ) AS size,
       c.conname AS constraint,
       c.confrelid::regclass AS referenced_table,
       'CREATE INDEX ' || c.conrelid::regclass || '_' || a.attname || '_idx ON ' || c.conrelid::regclass || ' (' || a.attname || ');' as fix
FROM pg_catalog.pg_constraint c
   /* enumerated key column numbers per foreign key */
   CROSS JOIN LATERAL
      unnest(c.conkey) WITH ORDINALITY AS x(attnum, n)
   /* name for each key column */
   JOIN pg_catalog.pg_attribute a
      ON a.attnum = x.attnum
         AND a.attrelid = c.conrelid
WHERE NOT EXISTS
        /* is there a matching index for the constraint? */
        (SELECT 1 FROM pg_catalog.pg_index i
         WHERE i.indrelid = c.conrelid
           /* it must not be a partial index */
           AND i.indpred IS NULL
           /* the first index columns must be the same as the
              key columns, but order doesn't matter */
           AND (i.indkey::smallint[])[0:cardinality(c.conkey)-1]
               OPERATOR(pg_catalog.@>) c.conkey)
  AND c.contype = 'f'
GROUP BY c.conrelid, c.conname, c.confrelid, a.attname
ORDER BY pg_catalog.pg_relation_size(c.conrelid) DESC;

          table           |   column    |  size   |              constraint               | referenced_table  |                                           fix                                            
--------------------------+-------------+---------+---------------------------------------+-------------------+------------------------------------------------------------------------------------------
 tx_in                    | redeemer_id | 2770 MB | tx_in_redeemer_id_fkey                | redeemer          | CREATE INDEX tx_in_redeemer_id_idx ON tx_in (redeemer_id);
 pool_offline_fetch_error | pmr_id      | 501 MB  | pool_offline_fetch_error_pmr_id_fkey  | pool_metadata_ref | CREATE INDEX pool_offline_fetch_error_pmr_id_idx ON pool_offline_fetch_error (pmr_id);
 delegation               | redeemer_id | 142 MB  | delegation_redeemer_id_fkey           | redeemer          | CREATE INDEX delegation_redeemer_id_idx ON delegation (redeemer_id);
 withdrawal               | redeemer_id | 105 MB  | withdrawal_redeemer_id_fkey           | redeemer          | CREATE INDEX withdrawal_redeemer_id_idx ON withdrawal (redeemer_id);
 stake_deregistration     | redeemer_id | 11 MB   | stake_deregistration_redeemer_id_fkey | redeemer          | CREATE INDEX stake_deregistration_redeemer_id_idx ON stake_deregistration (redeemer_id);
 pool_offline_data        | pmr_id      | 3320 kB | pool_offline_data_pmr_id_fkey         | pool_metadata_ref | CREATE INDEX pool_offline_data_pmr_id_idx ON pool_offline_data (pmr_id);
 script                   | tx_id       | 2352 kB | script_tx_id_fkey                     | tx                | CREATE INDEX script_tx_id_idx ON script (tx_id);
 collateral_tx_in         | tx_out_id   | 1512 kB | collateral_tx_in_tx_out_id_fkey       | tx                | CREATE INDEX collateral_tx_in_tx_out_id_idx ON collateral_tx_in (tx_out_id);
 reserved_pool_ticker     | pool_id     | 0 bytes | reserved_pool_ticker_pool_id_fkey     | pool_hash         | CREATE INDEX reserved_pool_ticker_pool_id_idx ON reserved_pool_ticker (pool_id);
```

**Comment by rknightion** [comment] 2021-12-02 11:38
I've just been able to replicate the reduction in block delete on my system. Although I do wonder, given the index is updated by postgres on every subsequent table INSERT, could this not have a negative performance impact once db-sync gets past the rollback?

**Comment by memewhale** [comment] 2021-12-02 19:30
I didn't measure it but syncing back the ~20k blocks seemed reasonably fast.

I also don't know which of the indexes had the most impact, but the block deletions taking up to a day is really hurting db-sync users

**Comment by ljttl3q04t** [comment] 2021-12-09 07:59
Because `Block` table has a lot of foreign keys, indexes and massive size...You can drop db and restore from snapshot instead

**Comment by erikd** [comment] 2021-12-09 08:40
> but the block deletions taking up to a day is really hurting db-sync users

What? How many blocks are being deleted? This really sounds like something is **WAY** wrong here.

**Comment by xdzurman** [comment] 2021-12-09 12:05
@erikd I suppose `Deleting 20768 blocks up to slot 46823508` as in the issue description. I can confirm a similar case where
```
[db-sync-node:Info:119] [2021-12-09 10:18:24.02 UTC] Deleting 10453 blocks up to slot 47478285 
```
has been ongoing for 2 hours with no progress.

**Comment by erikd** [comment] 2021-12-09 22:08
@xdzurman What is your sync speed like? I have not seen a rollback that small take more than a couple of minutes.

> has been ongoing for 2 hours with no progress. (Update: 3,5 hours without progress)

Pretty sure it is making progress, but that its not reporting it (because its all being done in PostgreSQL).

**Comment by erikd** [comment] 2021-12-10 03:51
Also `12.0.0` should never roll back that many blocks and longer term we hope to reduce it to basically zero.

**Comment by erikd** [comment] 2021-12-16 02:56
Just looking at this again:

```
> db-sync was stuck for many many hours here:
[db-sync-node:Info:772642] [2021-12-01 20:16:54.84 UTC] Rolling back to slot 46396728, hash 0b4e19943029e10894330f9988d25d1104b4503cd41a9f623992cd410fbeb4bc
[db-sync-node:Info:772642] [2021-12-01 20:16:54.90 UTC] Deleting 20768 blocks up to slot 46823508
```
by the time you see the second "Deleting X blocks" message, the rollback is **complete** and the rollback took less than a second.

The "db-sync was stuck for many many hours here" idea is not correct. After the rollback `db-sync` starts inserting blocks, but each block is not logged. `db-sync` tried to avoid excessive logging by only logging every block when `db-sync` is within 100 blocks of the chain tip. When `db-sync` is more than 100 blocks behind chain tip, only every 1000th block is logged.

**Comment by frog357** [comment] 2022-01-15 03:44
I'm using v11 still and I have been facing a rollback of 12k blocks for more than 24 hours on 2 different servers.

Jan 13 17:53:56 dbsync1 cardano-db-sync[883]: [db-sync-node:Info:134] [2022-01-13 22:53:56.18 UTC] Deleting 12143 blocks up to slot 50544807

**Comment by erikd** [comment] 2022-01-16 01:37
@frog357 If you are only rolling back 12k blocks, it should take less than 30 minutes. If you are seeing more than that check your postgres logs and configuration.

**Comment by erikd** [comment] 2022-01-17 00:08
Nearly all of the suggested indices are already in https://github.com/input-output-hk/cardano-db-sync/blob/master/schema/migration-3-0007-20211022.sql .

**Comment by erikd** [comment] 2022-01-17 00:08
Closing.

**Closed by erikd** 2022-01-17 00:08 UTC
Labels: bug

**Comment by reqlez** [comment] 2022-03-16 08:34
Just heads up, I created these additional indexes, and my DB sync time after OS restart went down from 4 hours to under 10 second after cardano-node starts. Indeed this fix works.

**Comment by grim-i-am** [comment] 2022-05-18 09:46
Keep in mind that if you build db-sync on one machine and then transfer to another, or if you download an already built binary, you must also transfer the schema folder as this is where the migrations reside.
