### ISSUE TITLE
missing reward for address

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#696] opened 2021-07-17 19:06 UTC
I have strange situation with the following address.

https://adapools.org/stake/stake1u9k0avpenksqz89x8qt7dehre0rtz4tesea24ne7s5crnvccqvyjr

test queries:

```sql
select reward.epoch_no, pool_hash.hash_raw as delegated_pool, reward.amount as lovelace
    from reward inner join stake_address on reward.addr_id = stake_address.id
    inner join pool_hash on reward.pool_id = pool_hash.id
    where stake_address.id = 86784 order by epoch_no desc ;
```

```sql
select sum(reward.amount) as lovelace
    from reward inner join stake_address on reward.addr_id = stake_address.id
    inner join pool_hash on reward.pool_id = pool_hash.id 
    where reward.pool_id=1621  and epoch_no =274 order by lovelace desc ;
```

This guy is normally getting rewards. for example E274 he got real almost 1500 ada, but in db-sync, with second query is there only 383 ada. when I look at non-iog sw, I can see that it he is getting rewards and also claims rewards normally, but not in db-sync:

https://cardanoscan.io/stakekey/6cfeb0399da0011ca63817e6e6e3cbc6b15579867aaacf3e853039b3?tab=withdrawalhistory

db-sync v10

**Comment by erikd** [comment] 2021-07-19 22:58
Making sure we had the same `id`s:
```sql
select id, view from stake_address where view = 'stake1u9k0avpenksqz89x8qt7dehre0rtz4tesea24ne7s5crnvccqvyjr' ; 
  id   |                            view                             
-------+-------------------------------------------------------------
 86784 | stake1u9k0avpenksqz89x8qt7dehre0rtz4tesea24ne7s5crnvccqvyjr
(1 row)
```
Now the query from above:
```sql
select reward.epoch_no, pool_hash.hash_raw as delegated_pool, reward.amount as lovelace
    from reward inner join stake_address on reward.addr_id = stake_address.id
    inner join pool_hash on reward.pool_id = pool_hash.id
    where stake_address.id = 86784 order by epoch_no desc ;
 epoch_no |                       delegated_pool                       |  lovelace  
----------+------------------------------------------------------------+------------
      276 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 | 1078553699
      274 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 | 1087197770
      272 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  603099838
      270 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  616495298
      266 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 | 1591530337
      265 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  608974620
      263 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  512335497
      262 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  513929191
      261 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  504594804
      260 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 | 1111011288
      259 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  815911548
      258 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  490681014
      254 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  616902432
      253 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  628527171
      250 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |          0
      247 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  718288874
      246 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  734670397
      245 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  727682324
      240 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  968162402
      235 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  925228051
      234 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  948607410
      230 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 | 1023668746
      225 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 |  831768859
      213 | \x29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5 | 1571824626
(24 rows)
```
and:
```sql
select sum(reward.amount) as lovelace
    from reward inner join stake_address on reward.addr_id = stake_address.id
    inner join pool_hash on reward.pool_id = pool_hash.id 
    where reward.pool_id=1621  and epoch_no =274 order by lovelace desc ;
  lovelace  
------------
 1470170988
(1 row)
```
@cardanians Do these results match yours?

**Comment by cardanians** [comment] 2021-07-20 05:29
@erikd 

no. we have different data absolutelly. question is - why?

![obrazek](https://user-images.githubusercontent.com/58650764/126266678-508d714b-70b0-404c-85d5-4ed2cf265423.png)

second result I have: 383831442

**Comment by erikd** [comment] 2021-07-20 05:39
Ok, if you have difference data to me, that is almost certainly https://github.com/input-output-hk/cardano-db-sync/issues/665 which has been fixed on `master` after `10.0.0/10.0.1` was released.

**Comment by cardanians** [comment] 2021-07-20 05:55
Yeah, i have 8d old 10.0.0, so looks like that.

Is possible release new version with this fix + #697 then? as im not sure if build from master is best option. thanks.

**Comment by erikd** [comment] 2021-07-20 05:56
Yeah, building from `master` is a bad idea. I have a fix for part of #697 , but I am still testing that and I am not sure that is the only problem.

**Comment by cardanians** [comment] 2021-07-20 06:08
maybe second problem can be if the next update stops after the fetch limit is exceeded (until re-registration). every day there should be an attempt despite these errors despite the previous errors. as some pools have unavailable meta file and they dont know about it, until adapools is displaying only pool id. and when they fix it then, data are not refetched again because limit exceeded (im not using yet this table, but should be maybe problem too)

**Comment by cardanians** [comment] 2021-07-25 04:51
@erikd is still on track fix release today?

**Comment by erikd** [comment] 2021-07-25 06:13
Today is Sunday. Zero chance of a release today.

**Comment by erikd** [comment] 2021-07-26 23:13
Working on this. Unlikley to be ready before the end of the week.

**Comment by cardanians** [comment] 2021-07-27 05:11
that's terrible.

**Comment by erikd** [comment] 2021-07-27 06:50
@cardanians It takes the time ti takes. There is nothing to do that can be done to make this faster without the possibility of introducing new bugs.

If you really must get your `db-sync` up and running before these fixes are complete, have you considered downrevving to whatever version you were running before?

**Comment by cardanians** [comment] 2021-07-27 07:31
I could revert to the original version assuming the structure was identical, but even that changes with each version (e.g. metadata storage, changing the logic for pool_hash_ids, as I recall). reverting back would make the next few days completely unnecessary. 

I firmly believe that fixing critical bugs like this is a priority, especially if a buggy release is still available and more and more people will have the same problem. I hope you will surprise positively with new release timing. 

Thank you in advance on behalf of all db-sync users.

**Comment by erikd** [comment] 2021-07-27 07:34
> reverting back would make the next few days completely unnecessary.

It should be a about 24 hours to re-sync.

> I firmly believe that fixing critical bugs like this is a priority,

This is the *only* thing I have been working on for the last week. It can't be higher priority than that.

**Comment by rynz** [comment] 2021-07-30 00:22
![image](https://user-images.githubusercontent.com/2523492/127581060-2359edcb-adca-48e5-8283-ea1a67b1fbcf.png)
Affected pools are now reporting less than 1% ROA (M) due to the miscalculation this bug has been causing for 5 epochs in a row, feeling the sting consistently now 😱

**Comment by erikd** [comment] 2021-07-30 03:01
@rynz what is that screen shot from?

**Comment by rynz** [comment] 2021-07-30 03:22
> @rynz where is that screen shot from?

https://adapools.org/spaas Rewards tab.

**Comment by reqlez** [comment] 2021-08-02 01:14
How you all guys doing with the bug hunting? Any good progress?

**Comment by erikd** [comment] 2021-08-02 06:06
Unfortunately we are not even at the bug hunting yet, because we still need to improve the way we detect that something is wrong.

**Comment by marco-martins** [comment] 2021-08-02 07:26
Same here https://adapools.org/pool/29df06255834d24d6a149224cf114a371bea08b64e7537e224a561a5

**Comment by ImpressiveSolutions** [comment] 2021-08-02 14:23
> Unfortunately we are not even at the bug hunting stage yet, because we still need to improve the way we detect that something is wrong.

Sorry what? This report is 16 days old.
In your favor i would say 8 days (the moment it is clear that it IS a bug).

And after 8(16) days, you are still not fixing, because you "improve the way we detect that something is wrong"?!

How does your "Quality Assurance"-System works? Does it even work?

**Comment by dcoutts** [comment] 2021-08-03 18:42
Here's a little explanation so people know what's going on here and understand why this is not trivial.

Firstly, there is no missing or wrong information in the ledger itself or how it is tracked in the node. The issue is all to do with how to we get the right information from the node into the database in a way that is _efficient_. The particular challenge is this: the reward payouts are not present in blocks, they are only known to the ledger rules in the tracking state. The design historically of db-sync has been that it's perfect for getting information from blocks, but this information does not come from blocks.

Furthermore, although db-sync does have access to the ledger state, getting the rewards from the ledger state is not that easy, because the node's ledger state is designed for its own purposes not to support client applications. There are two further complications:
1. Logically, the rewards are paid out exactly on the epoch boundary. But for DB performance it's really bad to wait to exactly the epoch performance and then insert a huge number of reward payouts. That approach causes stalls at the epoch boundary and that makes everyone grumpy. 
2. The reward accounts have to exist at that time for the rewards to be paid out. It's totally possible to unregister a stake address just before the epoch boundary and miss out on reward payouts. So we need a more complicated scheme where rewards are prepared in advance, but still deal accurately with the situation that reward accounts are unregistered before the boundary.

The approach we are taking to do this better (ie correct data and with decent performance) is to make a better interface between the ledger state updates and the database. We are adding a system where applying the next block to the ledger state also gives us useful information about the block that are based on the ledger state. In particular we will use this to report the calculation of the rewards prior to the epoch boundary, which will make it easier for db-sync to write out the rewards in advance of the epoch boundary. We will also need to devise a reasonable scheme with the database to deal with the issue of accurately reflecting the fact that rewards are not paid out to reward accounts for stake addresses that get unregistered.

**Comment by cardanians** [comment] 2021-08-03 19:22
Thank you for your comprehensive reply @dcoutts 

In any case, it doesn't explain why a version with several bugs was released and QA passed, or why it hasn't been removed from releases until now. That's terribly irresponsible to other db-sync users tbh. 

Anyway the current bug with reward calculations is too for addresses that haven't moved anything maybe half a year.

Is there any realistic estimate of a resolution? 

If it's a long term fix, wouldn't it be worth releasing a new release (as there are "Minor update of database schema.") with at least the #697 fix and temporarily use the original, working, end of epoch reward "heavy" recalculation?

**Comment by mmahut** [comment] 2021-08-05 18:56
I would like to point out I strongly share the concerns in this thread. We (and number of our partners) did not upgrade to 10.0.1 as it is far from production ready, given the data it provides are inconsistent in a way this version is not really usable.

As far as I know, Adalite (VacuumLabs) and Yoroi (Emurgo) had to roll back to previous versions due to this reason, so it is worrisome to see that 10.0.1 is being recommended as an valid upgrade and is has not been pulled out as an release.

This is one of the most critical Cardano components, yet it seems it is not treated as such.

**Comment by erikd** [comment] 2021-08-07 23:21
This is not being ignored. This has been the main focus of 95% of my time for the last several weeks. I also have input from people on the `cardano-ledger-specs` team. This is a difficult problem. Anyone expecting an instant solution will be disappointed.

**Comment by kderme** [comment] 2021-08-09 00:29
I believe the issue here is a Unique key in the Reward table which didn't allow both `member` and `leader` rewards to be inserted in the db, hence the difference in the results between https://github.com/input-output-hk/cardano-db-sync/issues/696#issuecomment-882914507 and https://github.com/input-output-hk/cardano-db-sync/issues/696#issuecomment-883070951.

**Comment by cardanians** [comment] 2021-08-09 09:40
@kderme so the discussion around this was unnecessary and a new release with fixes could have been released long ago? wtf...

**Comment by erikd** [comment] 2021-08-11 00:39
@cardanians Yes, in hindsight these issue have probably already been fixed (the final one was this week). However until early this week we had no way of verifying it. Partial verification landed early this week and gets us 90% certainty. We are still waiting for a new feature from `cardano-ledger-specs` that will get us to at least 99% certainty.

**Comment by erikd** [comment] 2021-08-11 07:09
https://github.com/input-output-hk/cardano-db-sync/issues/749 is related.

**Closed** 2021-09-06 08:31 UTC

**Comment by xdzurman** [comment] 2021-09-08 08:45
@erikd Seeing you closed this via the commit, could the fix be patch released until the hard fork? Or is it safe to build a docker container from the commit?

**Comment by erikd** [comment] 2021-09-10 00:53
This issue has been fixed, but https://github.com/input-output-hk/cardano-db-sync/issues/796 is a related problem.

I would recommend against using master because its still a moving target.
