### ISSUE TITLE
InsertRedeemerTx fail loop

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#999] opened 2021-12-26 22:31 UTC
**OS**
Your OS: Linux

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): `master` at c064503475c8d7f514544e4e39f726f8c5f3f013
PostgreSQL version: 3.5-0+deb11u1 

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: cabal

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): command line

`db-sync` has fallen into a fail loop with the following logs:
```
[2021-12-26 22:13:04.20 UTC] Cardano.Db tip is at slot 48938827, block 6675915
[2021-12-26 22:13:04.20 UTC] Running DB thread
[2021-12-26 22:13:04.20 UTC] Running Offline fetch thread
[2021-12-26 22:13:04.22 UTC] Rolling back to slot 48930090, hash b6ade4b1af0a88b310de1104602f09e66895deaff6960ba706dfb5f00f974308
[2021-12-26 22:13:04.22 UTC] Deleting 416 blocks up to slot 48938827
[2021-12-26 22:13:53.34 UTC] Blocks deleted
[2021-12-26 22:14:18.60 UTC] Found snapshot file for slot 48930090, hash b6ade4b1af0a88b310de1104602f09e66895deaff6960ba706dfb5f00f974308
[2021-12-26 22:14:52.44 UTC] Error: insertRedeemertx hash 8b0fb3f12cac47d43e3a29f24b858fa00c07fc71ed57b10274805c8c984d176c
[2021-12-26 22:14:52.44 UTC] Shutting down DB thread
[2021-12-26 22:14:52.44 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"} event: Miniprotocol (MiniProtocolNum 5) InitiatorDir terminated cleanly
[2021-12-26 22:14:53.45 UTC] Identity Restarting Subscription after 109.347537731s desired valency 1 current valency 0
[2021-12-26 22:14:53.45 UTC] Identity Starting Subscription Worker, valency 1
[2021-12-26 22:14:53.45 UTC] Identity Connection Attempt Start, destination LocalAddress "../cardano-node/state-node-mainnet/node.socket"
[2021-12-26 22:14:53.45 UTC] Identity Connection Attempt End, destination LocalAddress "../cardano-node/state-node-mainnet/node.socket" outcome: ConnectSuccessLast
[2021-12-26 22:14:53.45 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073),(NodeToClientV_4,TInt 764824073),(NodeToClientV_5,TInt 764824073),(NodeToClientV_6,TInt 764824073),(NodeToClientV_7,TInt 764824073),(NodeToClientV_8,TInt 764824073),(NodeToClientV_9,TInt 764824073),(NodeToClientV_10,TInt 764824073)]))
[2021-12-26 22:14:53.45 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_10 (TInt 764824073))
[2021-12-26 22:14:53.45 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"} event: Handshake Client end, duration 0.00149699s
[2021-12-26 22:14:53.45 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"} event: State: Mature
[2021-12-26 22:14:53.45 UTC] Starting chainSyncClient
[2021-12-26 22:14:53.47 UTC] Identity Required subscriptions started
```
This *looks* like the a problem when a Redeemer is inserted into the database, and then is not properly removed on rollback, so that when it rolls forward if fails to insert.

I am currently on PTO (Paid Time Off) and have plans for the day. I can look at this more closely in about 8 hours. Will try to come up with a workaround ASAP.

**Comment by erikd** [comment] 2021-12-26 22:33
The workaround would be:
* Halt `db-sync` as soon as it detects the error.
* Delete from the database the `redeemer` enty that is causing the problem.
* Restart `db-sync`.
*

**Comment by kderme** [comment] 2021-12-27 01:21
It looks like the txIn of a 'spend' redeemer could not be resolved. The txIn is created in tx 'b6ade4b1af0a88b310de1104602f09e66895deaff6960ba706dfb5f00f974308'. I think the root cause is a recent optimization in master, which made the txIn of a block grouped and inserted in batches. This means inputs created and referenced within the same block may not be present yet. The function 'resolveTxInputs' is adjusted to handle this case. However there is a second place where inputs are resolved (in `insertRedeemer` for inputs referenced by redeemers) that I had totally forgotten about.

**Comment by kderme** [comment] 2021-12-27 01:33
data seem to verify this:

tx [8b0fb3f12cac47d43e3a29f24b858fa00c07fc71ed57b10274805c8c984d176c](https://explorer.cardano.org/en/transaction?id=8b0fb3f12cac47d43e3a29f24b858fa00c07fc71ed57b10274805c8c984d176c) creates a script output at `addr1wy2mjh76em44qurn5x73nzqrxua7ataasftql0u2h6g88lc3gtgpz`.

Another tx [5e2ec3352bf866301ffb7a634330f5f7ec5a10f104f2c0b5dce103f804a50546](https://explorer.cardano.org/en/transaction?id=5e2ec3352bf866301ffb7a634330f5f7ec5a10f104f2c0b5dce103f804a50546) in the same block `6675915`  consumed this outputs. The redeemer input cannot be resolved and db-sync crashes.

Solution is to either avoid resolving inputs in multiple places or fix `insertRedeemer` to handle this case, by passing to it the in memory outputs `[ExtendedTxOut]` like in `resolveTxInputs`

**Comment by kderme** [comment] 2021-12-27 01:37
The batch insert optimization was introduced after release 12, so this should be only in master.

**Comment by erikd** [comment] 2021-12-27 07:00
I must have been running `master` rather than `12.0.1` (which is 100% fine).

We will still need to get `master` sorted out, but that can wait until we are back on the job.

**Comment by thakkery** [comment] 2021-12-31 14:45
I also ran into this when using docker-compose to restart a docker node. The full stacktrace is below:

`
[2021-12-31 14:42:51.07 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync_1  | [db-sync-node.Subscription:Warning:47] [2021-12-31 14:42:51.10 UTC] Identity Failed to start all required subscriptions
cardano-db-sync_1  | [db-sync-node.Subscription:Notice:47] [2021-12-31 14:42:52.10 UTC] Identity Restarting Subscription after 1.026028646s desired valency 1 current valency 0
cardano-db-sync_1  | [db-sync-node.Subscription:Notice:47] [2021-12-31 14:43:01.08 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync_1  | [db-sync-node.Subscription:Notice:54] [2021-12-31 14:43:01.08 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync_1  | [db-sync-node.Subscription:Error:54] [2021-12-31 14:43:01.08 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
`

The above keeps repeating over and over. I'll leave the node running for a while in case the issue resolves itself after the node finishes syncing

**Comment by erikd** [comment] 2021-12-31 22:38
@thakkery This can only happen with the `master` branch. **DO NOT** use the `master` branch. Use the latest release tag which is currently `12.0.1`.

**Comment by thakkery** [comment] 2022-01-03 04:24
You are right it was a different bug, found the right ticket

**Closed** 2022-01-16 03:19 UTC
Labels: bug
