### ISSUE TITLE
11.0.0 rewards issue

### ISSUE THREAD

**Issue by roccomuso** [input-output-hk/cardano-db-sync#801] opened 2021-09-09 15:46 UTC
Release 11.0.0 has known problems with rewards. Will it be fixed before the hardfork?

**Comment by erikd** [comment] 2021-09-10 00:44
I am still working on it, but there is zero chance of it being fixed for the HF.

**Comment by erikd** [comment] 2021-09-11 06:41
Closing this as a duplicate of #796.

**Closed by erikd** 2021-09-11 06:41 UTC
