### ISSUE TITLE
testnet, rewards differ between ledger and db-sync

### ISSUE THREAD

**Issue by kris-76** [input-output-hk/cardano-db-sync#856] opened 2021-09-28 15:46 UTC
**OS**
Your OS: Ubuntu 20.04

[db-sync-node:Info:6] [2021-09-28 15:40:53.89 UTC] Schema migration files validated
[db-sync-node:Info:6] [2021-09-28 15:40:53.89 UTC] Running database migrations
[db-sync-node:Info:6] [2021-09-28 15:40:56.54 UTC] Using byron genesis file from: "/home/ubuntu/cardano/testnet/testnet-byron-genesis.json"
[db-sync-node:Info:6] [2021-09-28 15:40:56.54 UTC] Using shelley genesis file from: "/home/ubuntu/cardano/testnet/testnet-shelley-genesis.json"
[db-sync-node:Info:6] [2021-09-28 15:40:56.54 UTC] Using alonzo genesis file from: "/home/ubuntu/cardano/testnet/testnet-alonzo-genesis.json"
[db-sync-node:Info:6] [2021-09-28 15:40:56.61 UTC] NetworkMagic: 1097911063
[db-sync-node:Info:6] [2021-09-28 15:40:56.64 UTC] Initial genesis distribution present and correct
[db-sync-node:Info:6] [2021-09-28 15:40:56.64 UTC] Total genesis supply of Ada: 41999999999.999903
[db-sync-node:Info:6] [2021-09-28 15:40:56.64 UTC] Inserting Shelley Genesis distribution
[db-sync-node:Info:6] [2021-09-28 15:40:56.64 UTC] localInitiatorNetworkApplication: connecting to node via "/home/ubuntu/cardano/testnet/db/node.socket"
[db-sync-node.Subscription:Notice:65] [2021-09-28 15:40:56.64 UTC] Identity Starting Subscription Worker, valency 1
[db-sync-node.Subscription:Notice:66] [2021-09-28 15:40:56.64 UTC] Identity Connection Attempt Start, destination LocalAddress "/home/ubuntu/cardano/testnet/db/node.socket"
[db-sync-node.Subscription:Notice:66] [2021-09-28 15:40:56.64 UTC] Identity Connection Attempt End, destination LocalAddress "/home/ubuntu/cardano/testnet/db/node.socket" outcome: ConnectSuccessLast
[db-sync-node.Handshake:Info:66] [2021-09-28 15:40:56.64 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/home/ubuntu/cardano/testnet/db/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 1097911063),(NodeToClientV_2,TInt 1097911063),(NodeToClientV_3,TInt 1097911063),(NodeToClientV_4,TInt 1097911063),(NodeToClientV_5,TInt 1097911063),(NodeToClientV_6,TInt 1097911063),(NodeToClientV_7,TInt 1097911063),(NodeToClientV_8,TInt 1097911063),(NodeToClientV_9,TInt 1097911063)]))
[db-sync-node.Handshake:Info:66] [2021-09-28 15:40:56.64 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/home/ubuntu/cardano/testnet/db/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_9 (TInt 1097911063))
[db-sync-node.Mux:Info:66] [2021-09-28 15:40:56.64 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/home/ubuntu/cardano/testnet/db/node.socket"} event: Handshake Client end, duration 0.000456294s
[db-sync-node.Mux:Info:67] [2021-09-28 15:40:56.64 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/home/ubuntu/cardano/testnet/db/node.socket"} event: State: Mature
[db-sync-node:Info:70] [2021-09-28 15:40:56.64 UTC] Starting chainSyncClient
[db-sync-node:Info:70] [2021-09-28 15:40:56.66 UTC] Cardano.Db tip is at slot 6782373, block 1851160
[db-sync-node:Info:75] [2021-09-28 15:40:56.66 UTC] Running DB thread
[db-sync-node:Info:75] [2021-09-28 15:40:56.67 UTC] Rolling back to slot 6782373, hash 41241024b08ec38913fda0269d9f195f6df104efda1c4f327855241463d2e415
[db-sync-node.Subscription:Notice:65] [2021-09-28 15:40:56.67 UTC] Identity Required subscriptions started
[db-sync-node:Info:75] [2021-09-28 15:40:56.67 UTC] No blocks need to be deleted
[db-sync-node:Info:75] [2021-09-28 15:40:57.32 UTC] Found snapshot file for slot 6782373, hash 41241024b08ec38913fda0269d9f195f6df104efda1c4f327855241463d2e415
[db-sync-node:Info:78] [2021-09-28 15:40:57.40 UTC] getHistoryInterpreter: acquired
[db-sync-node:Info:87] [2021-09-28 15:40:57.40 UTC] Running Offline fetch thread
[db-sync-node:Info:75] [2021-09-28 15:40:57.40 UTC] thisIsAnUglyHack: Main thead
[db-sync-node:Info:75] [2021-09-28 15:40:57.40 UTC] File ../../cardano-src/cardano-db-sync/ledger-state/testnet/6782373-41241024b0-85.lstate exists
[db-sync-node:Info:75] [2021-09-28 15:40:57.40 UTC] Starting at epoch 86
[db-sync-node:Info:75] [2021-09-28 15:40:57.40 UTC] Handling 256 stakes for epoch 86 slot 6782400, hash 3fdfbd1bed0358d16778ae4d0bd5e46212cff3d1a9a155a1fb8574fbb7f10497
[db-sync-node:Warning:75] [2021-09-28 15:40:57.55 UTC] validateEpochRewards: rewards earned in epoch 84 expected total of 158768.12877 ADA but got 158468.12877 ADA
dbMap length: 27
ledgerMap length: 27
diffMap length: 3
e03412de65e523666ef5df0a7c3db510b99b0553b67f324f0ba215af82 (118244, 1): [(RwdMember,DbLovelace 118244)], Coin 100118244
e07821cc41d016e17e2f6e37a8c1ba8a3caaaf52d44b80a557b4cc4d98 (128667, 1): [(RwdMember,DbLovelace 128667)], Coin 100128667
e09cd7cd070bbcc65f75b460a3f4462e3445f11a7f2f1a49825a10f88d (128667, 1): [(RwdMember,DbLovelace 128667)], Coin 100128667
Rewards differ between ledger and db-sync.
Please report at https://github.com/input-output-hk/cardano-db-sync/issues.

ubuntu@ip-172-31-86-6:~/cardano/testnet$ cardano-db-sync --version
cardano-db-sync 11.0.0 - linux-x86_64 - ghc-8.10
git revision e2d5cf8068c030ed3c8006ce008b4100fbaad581

ubuntu@ip-172-31-86-6:~/cardano/testnet$ cardano-node --version
cardano-node 1.30.0 - linux-x86_64 - ghc-8.10
git rev ed7fdbf65f40f8e194850b87dd8c631fe26154e6

**Comment by sorki** [comment] 2021-09-28 15:49
Duplicate of #805.

**Closed** 2021-09-29 01:36 UTC
Labels: bug
