### ISSUE TITLE
Extremely slow ingestion of new entries

### ISSUE THREAD

**Issue by khelle** [input-output-hk/cardano-db-sync#1062] opened 2022-02-17 10:55 UTC
**OS**
Ubuntu 18.04.5 LTS (Bionic Beaver)

**Versions**
cardano-db-sync version 12.0.2
postgresql version 10.19

**Build/Install Method**
Build from source using nix-build

**Run method**
```
/home/ada/cardano-db-sync/db-sync-node/bin/cardano-db-sync-extended --config /home/ada/cardano-db-sync/config/mainnet-config.yaml --socket-path /home/ada/db/node.socket --state-dir /home/ada/ledger-state/mainnet --schema-dir /home/ada/cardano-db-sync/schema
```

**Problem Report**
Ingestion of new records has gone painfuly slow somewher around epoch 250. DB-sync was able to catch up from genesis to 250 in a day, then the performance dramatically decreased. Currently my db-sync is at epoc 286 and is ingesting around 1 epoch per 1.5 hrs. That means it will take 3 more days to complete the ingestion and also it means the current time of syncing network from zero is around 6 days. It is extremely slow, even ETH synchronizes much faster. Is there anything I can do to make it speed up?

On a separate note, I am unable to check this now, but I am almost certain older versions needed half of that time to go from zero to fully-synced. What happened? Or was it only my imagination?

**Comment by ArturWieczorek** [comment] 2022-02-17 11:09
As for this:
> Is there anything I can do to make it speed up?

Yes, you can use snapshots. 
In [releases](https://github.com/input-output-hk/cardano-db-sync/releases) section of GH there is a table with links to snapshots for each release so you can use this [link](https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#12/) to download state snapshot for `v12`.

Here is a [document](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/state-snapshot.md) that describes this feature and explains how to create and restore state from snapshots.

**Comment by erikd** [comment] 2022-02-17 22:53
> DB-sync was able to catch up from genesis to 250 in a day, then the performance dramatically decreased.

Newer epochs contain *vasty* more data than older epochs. Eg run the query:
```sql
select * from epoch ; 
```
and look at the `tx_count` column. At epoch 100, each epoch had about 8000 transactions. At epoch 200 it had grown to about 20000 transactions per epoch. At epoch 300, its about 35000 transactions. For the last couple of epochs:

```sql
select * from epoch where no >= 300 ; 
 id  |      out_sum       |     fees     | tx_count | blk_count | no  |     start_time      |      end_time       
-----+--------------------+--------------+----------+-----------+-----+---------------------+---------------------
 301 |  41397840177266484 |  88206195240 |   391299 |     21225 | 300 | 2021-11-01 21:49:05 | 2021-11-06 21:44:35
 302 |  33148201915900395 |  97036953903 |   451157 |     20989 | 301 | 2021-11-06 21:46:27 | 2021-11-11 21:44:15
 303 |  39411705509214974 | 202279497524 |  1033931 |     21203 | 302 | 2021-11-11 21:46:52 | 2021-11-16 21:44:14
 304 |  31808650630788618 | 103395856418 |   488235 |     20948 | 303 | 2021-11-16 21:45:05 | 2021-11-21 21:44:23
 305 |  41119279092669542 | 308293830822 |  1566974 |     21095 | 304 | 2021-11-21 21:44:55 | 2021-11-26 21:43:39
 306 |  31316579883453929 | 156264770889 |   769219 |     21025 | 305 | 2021-11-26 21:45:18 | 2021-12-01 21:44:40
 307 |  38644324751006758 | 114439696442 |   531293 |     21141 | 306 | 2021-12-01 21:46:31 | 2021-12-06 21:44:50
 308 |  29271525504982268 | 127647415455 |   604359 |     20910 | 307 | 2021-12-06 21:45:26 | 2021-12-11 21:43:57
 309 |  18080504620762237 | 103811542089 |   427399 |     21033 | 308 | 2021-12-11 21:45:50 | 2021-12-16 21:43:58
 310 |  13560377046033274 | 134784675796 |   553388 |     20804 | 309 | 2021-12-16 21:45:46 | 2021-12-21 21:44:45
 311 |  12210427846799865 | 116225490530 |   475918 |     21045 | 310 | 2021-12-21 21:46:06 | 2021-12-26 21:44:36
 312 |  12815272307603394 | 107642266965 |   452652 |     21090 | 311 | 2021-12-26 21:45:00 | 2021-12-31 21:44:46
 313 |  12414570555178621 | 135522429378 |   501383 |     20821 | 312 | 2021-12-31 21:44:58 | 2022-01-05 21:44:40
 314 |  12799132332645463 | 182577641027 |   643762 |     20267 | 313 | 2022-01-05 21:45:31 | 2022-01-10 21:44:33
 315 |  20300614123659385 | 192127658577 |   643632 |     20390 | 314 | 2022-01-10 21:46:48 | 2022-01-15 21:44:03
 316 |  31390388454243129 | 269870823296 |   906299 |     20182 | 315 | 2022-01-15 21:46:27 | 2022-01-20 21:44:38
 317 |  53565358148257632 | 252763162151 |   841394 |     20141 | 316 | 2022-01-20 21:44:59 | 2022-01-25 21:44:50
 318 |  37775838105316315 | 252123552102 |   756297 |     20478 | 317 | 2022-01-25 21:45:22 | 2022-01-30 21:44:31
 319 |  34544504178807063 | 233870176809 |   655198 |     20284 | 318 | 2022-01-30 21:45:49 | 2022-02-04 21:44:26
 320 |  40813881112218506 | 242157748335 |   650534 |     20414 | 319 | 2022-02-04 21:45:26 | 2022-02-09 21:44:03
 322 |  53580674260390750 | 154707263114 |   418253 |     12431 | 321 | 2022-02-14 21:45:00 | 2022-02-17 22:50:26
 321 | 105085917821177706 | 233553475002 |   601903 |     20284 | 320 | 2022-02-09 21:45:46 | 2022-02-14 21:44:31
(22 rows)
```
the current database size is 100 Gigabytes. It takes a non-trvial amount of time to insert that much data.

Hover, if you just want a database with all the data, use the snapshots as suggested by @ArturWieczorek .

**Comment by erikd** [comment] 2022-02-23 06:01
@khelle This is not a bug, `db-sync` is operating within the bounds of physics. Can this be closed?

**Comment by erikd** [comment] 2022-03-10 00:57
Closing this.

**Closed by erikd** 2022-03-10 00:57 UTC
Labels: bug
