### ISSUE TITLE
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

### ISSUE THREAD

**Issue by RdeWilde** [input-output-hk/cardano-db-sync#1230] opened 2022-08-16 21:07 UTC
**OS**
Your OS: Ubuntu

**Versions**
The `db-sync` version: 13.0.3
PostgreSQL version: 11.5

**Build/Install Method**
Ansible

**Run method**
Docker

**Additional context**
On a fresh start, I get this error:
```
Connecting to network specified in configuration.yaml
Downloading snapshot https://update-cardano-mainnet.iohk.io/cardano-db-sync/13/db-sync-snapshot-schema-13-block-7601999-x86_64.tgz ...
** Resuming transfer from byte position 16700764391
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 28.2G    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```
And the container restarts.

**Problem Report**
It worked before. I found something about Cloudflare not supporting it, but that would not make sense because then everybody should have this problem.

For me the only way to continue was to go dirty
```
$ sudo rm /var/lib/docker/overlay2/c20326b79e4fc73e0541ef1da580d09078d763fa22bd4343b624e3170985e9ea/diff/db-sync-snapshot-schema-13-block-7601999-x86_64.tgz
```

**Comment by tmcgilchrist** [comment] 2022-08-19 23:00
Duplicate of https://github.com/input-output-hk/cardano-db-sync/issues/1149

**Closed by tmcgilchrist** 2022-08-19 23:00 UTC
Labels: bug
