### ISSUE TITLE
Monitoring: Explorer db block divergence issue

### ISSUE THREAD

**Issue by sevanspowell** [input-output-hk/cardano-db-sync#154] opened 2020-06-25 02:41 UTC
cardano-db-sync service seems to have block divergence issues if the cardano-node service is restarted while it is running.

https://jira.iohk.io/browse/CD-56

**Comment by sevanspowell** [comment] 2020-06-25 04:03
The devops team started seeing block divergence alerts on the explorer node of the ff network (see [this graph|https://monitoring.ff.dev.cardano.org/prometheus/graph?g0.range_input=12h&g0.end_input=2020-06-23%2020%3A28&g0.expr=abs(cardano_node_ChainDB_metrics_blockNum_int%7Balias%3D~%22explorer.*%22%7D%20-%20on()%20db_block_height%7Balias%3D~%22explorer.*%22%7D)%20%3E%205&g0.tab=0).]

Investigating, we saw that the metrics endpoint was behind the cardano-db-sync.service logs:
  
[root@explorer:~]# curl -s localhost/metrics2/exporter | grep -v '#' 
db_block_height 63710.0
remote_tip_height 63710.0

[root@explorer:~]# journalctl -f -u cardano-db-sync.service 
 insertShelleyBlock: slot 1729944, block 69956
 
[root@explorer:~]# # It's further ahead: 69956 
 
[root@explorer:~]# # But it should be reporting that metric in the endpoint above, where it shows 63710.... 
 
[root@explorer:~]# systemctl restart cardano-db-sync.service 
 
[root@explorer:~]# journalctl -f -u cardano-db-sync.service -ocat 
insertShelleyBlock: slot 1730011, block 69959

[root@explorer:~]# curl -s localhost/metrics2/exporter | grep -v '#' 
db_block_height 69959.0
remote_tip_height 69959.0

[root@explorer:~]# # Now the metrics endpoint is reporting correctly in sync with what the journalctl service is reporting...

I've attached the logs (in JIRA) for both the cardano-node and cardano-db-sync services from around the time we first started seeing the issue (2020-06-23 ~12:50 UTC). It seems that time corresponds exactly to a restart of cardano-node. This may or may not be related.

**Comment by sevanspowell** [comment] 2020-06-25 04:05
This also occurred on the shelley-testnet:

 

 
```
# Metrics are behind

[root@explorer:~]# curl localhost/metrics2/exporter
db_block_height 3381.0
remote_tip_height 3381.0

[root@explorer:~]# journalctl -f -u cardano-db-sync.service | less
 insertShelleyBlock: slot 117360, block 5307
 
# Restart

[root@explorer:~]# systemctl restart cardano-db-sync.service
[root@explorer:~]# journalctl -f -u cardano-db-sync.service | less
insertShelleyBlock: slot 117400, block 5308

# Metrics are no longer behind

[root@explorer:~]# curl localhost/metrics2/exporter
db_block_height 5308.0
remote_tip_height 5308.0
```

**Comment by rhyslbw** [comment] 2020-08-10 03:12
@sevanspowell Is this still an issue?

**Comment by johnalotoski** [comment] 2020-08-14 15:40
Yes, it is.  We see this happening every few days.

**Comment by erikd** [comment] 2020-08-14 21:30
I have some extra debug on the branch `erikd/metrics` (just rebased agains master). You need to run that,

**Comment by erikd** [comment] 2021-01-19 22:20
Apparently this still is an issue, but not one that people have been making a fuss about.

As before I have not yet been able to reproduce this or get any decent debug from anywhere. I currently have the following running (which poll the metrics server 4 times every second):
```
while true ; do curl -s http://127.0.0.1:8080 | grep ^remote_tip_height ; sleep 0.25 ; done
```

**Comment by sevanspowell** [comment] 2021-01-21 04:20
@erikd A couple of questions about that command:
- Does `http://127.0.0.1:8080` report the same metrics as `localhost/metrics2/exporter` (i.e. the metrics reported by cardano-db-sync-extended)?
- Are you comparing the output of that command with the logs of `cardano-db-sync`?
- Have you simulated restarting cardano-node without restarting cardano-db-sync? Say every 2 hours? 

It seems the restarting of cardano-node and this issue are related:

> Again, this divergence coincides with a restart of cardano-node without a corresponding restart of cardano-db-sync (we started seeing the issue around 200-06-24 15:10, which is when cardano-node was restarted).

**Comment by erikd** [comment] 2021-01-21 04:41
Ah ok, `localhost/metrics2/exporter` doesn't work on my machine (HTTP 404) probably because its uses part of the Nix infrastructure.

**Comment by erikd** [comment] 2021-01-21 05:13
Ok, keeping `db-sync` running but restarting the `node` triggers this reliably.

**Comment by sevanspowell** [comment] 2021-01-21 05:16
Ooh yay!

**Comment by erikd** [comment] 2021-01-24 23:55
This is odd. If I log the remote node block height, i can see the block height incrementing, but the metrics of the HTTP port remain unchanged.

**Comment by erikd** [comment] 2021-01-25 00:30
The problem is now understood.

* `registerMetricsServer` registers the metrics and creates a server inside an `async`.
* When the node dies the `cancel` on the `async` is never called and that `async` remains alive.
* `registerMetricsServer` is called again, and registers a new metric and server.

This can probably be fixed with a `bracket`.

**Closed** 2021-01-25 02:00 UTC
