### ISSUE TITLE
some orphaned rewards are not shown in `orphaned_reward` table

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-db-sync#684] opened 2021-07-08 08:06 UTC
For scenario where stake address is deregistered, the orphaned rewards are not shown in the `orphaned_reward` table.

### Steps to reproduce:

* register and delegate stake address, check the registration epoch in db:
```
shelley_qa_tag_10=# select stake_registration.*, block.block_no, block.epoch_no from stake_registration
shelley_qa_tag_10-#     inner join tx on tx.id = stake_registration.tx_id
shelley_qa_tag_10-#     inner join block on tx.block_id = block.id
shelley_qa_tag_10-#     where stake_registration.addr_id = 2829 order by epoch_no asc ;
 id  | addr_id | cert_index | tx_id | block_no | epoch_no 
-----+---------+------------+-------+----------+----------
 885 |    2829 |          0 | 27141 |  1297117 |     3816
(1 row)
```

* after several epochs, deregister the stake address, check deregistration epoch in db:
```
shelley_qa_tag_10=# select stake_deregistration.*, block.block_no, block.epoch_no from stake_deregistration
shelley_qa_tag_10-#     inner join tx on tx.id = stake_deregistration.tx_id
shelley_qa_tag_10-#     inner join block on tx.block_id = block.id
shelley_qa_tag_10-#     where stake_deregistration.addr_id = 2829 order by epoch_no asc ;
 id  | addr_id | cert_index | tx_id | block_no | epoch_no 
-----+---------+------------+-------+----------+----------
 238 |    2829 |          0 | 27144 |  1301084 |     3827
(1 row)
```

* check that the address kept received rewards while it was registered (last `epoch_no` should be _deregistration epoch - 2_):
```
shelley_qa_tag_10=# select * from reward where addr_id = 2829 and epoch_no >= 3800 ;
  id   | addr_id |  type  | amount | epoch_no | pool_id 
-------+---------+--------+--------+----------+---------
 68605 |    2829 | member | 121039 |     3820 |       3
 68635 |    2829 | member |  99125 |     3821 |       3
 68664 |    2829 | member | 109972 |     3822 |       3
 68693 |    2829 | member |  95739 |     3823 |       3
 68723 |    2829 | member | 109854 |     3824 |       3
 68753 |    2829 | member | 111134 |     3825 |       3
(6 rows)
```

* rewards that were supposed to be received after _deregistration epoch_ (3826 and 3827) should be listed in `orphaned_reward`, but are missing:
```
shelley_qa_tag_10=# select * from orphaned_reward where addr_id = 2829 and epoch_no >= 3800 ;
 id | addr_id | type | amount | epoch_no | pool_id 
----+---------+------+--------+----------+---------
(0 rows)
```

* check that the pool was creating blocks and received rewards, so the deregistered stake address was eligible for rewards:
```
# select epoch_no, count(epoch_no) as num_rewards from reward where (pool_id = 3 and epoch_no >= 3825 and epoch_no <= 3830) group by epoch_no;
 epoch_no | num_rewards
----------+-------------
     3825 |          22
     3826 |          21
     3827 |          21
     3828 |          21
     3829 |          21
     3830 |          21
(6 rows)
```

**Comment by erikd** [comment] 2021-07-08 08:15
Duplicate of #683 .

**Closed by erikd** 2021-07-08 08:15 UTC
