### ISSUE TITLE
Cardano DB-Sync ExitFailure 3

### ISSUE THREAD

**Issue by got3nks** [input-output-hk/cardano-db-sync#181] opened 2020-07-11 09:36 UTC
Cardano DB-Sync always crash with the following error.

```
postgres_1_97b8bbe6330b | 2020-07-11 09:34:58.764 UTC [87] ERROR:  column "slots_per_epoch" contains null values
postgres_1_97b8bbe6330b | 2020-07-11 09:34:58.764 UTC [87] CONTEXT:  SQL statement "ALTER TABLE "meta" ADD COLUMN "slots_per_epoch" INT8 NOT NULL"
postgres_1_97b8bbe6330b | 	PL/pgSQL function migrate() line 7 at EXECUTE
postgres_1_97b8bbe6330b | 2020-07-11 09:34:58.764 UTC [87] STATEMENT:  SELECT migrate() ;
cardano-db-sync_1_d8338f03636b | ExitFailure 3
cardano-db-sync_1_d8338f03636b |
cardano-db-sync_1_d8338f03636b | Errors in file: /tmp/migrate-2020-07-11T093458.log
cardano-db-sync_1_d8338f03636b |
```

**Comment by erikd** [comment] 2020-07-11 22:07
You did not specify the version of `db-dync` you are using, nor did you specify what network you are connecting to.

This is likely to be a duplicate of https://github.com/input-output-hk/cardano-db-sync/issues/177 .

**Comment by got3nks** [comment] 2020-07-12 09:04
I'm using latest Docker images. As I read on `db-sync` release notes:

`This release requires the database to be dropped and recreated.`

How to do so?

**Comment by rhyslbw** [comment] 2020-07-13 01:19
@got3nks 
I've just added some info to the Wiki, https://github.com/input-output-hk/cardano-db-sync/wiki/Docker#rebuild-database-during-version-upgrade

**Closed by rhyslbw** 2020-07-13 01:19 UTC
