### ISSUE TITLE
Restore snapshot manually

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/cardano-db-sync#1158] opened 2022-06-16 23:14 UTC
I've never managed to restore a snapshot from IOHK. The connection always dropped in the middle and it cannot resume. I can download the snapshot from browser sometimes. How can I restore it locally?

```
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

** Resuming transfer from byte position 16697405664

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0 25.2G    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```

**Comment by erikd** [comment] 2022-06-17 02:54
This is a duplicate of #1149 .

**Closed by erikd** 2022-06-17 02:54 UTC
Labels: bug
