### ISSUE TITLE
DB Sync snapshots not getting updated anymore

### ISSUE THREAD

**Issue by pyromaniac3010** [input-output-hk/cardano-db-sync#1307] opened 2022-11-18 15:32 UTC
Hi,

the latest snapshot in https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#13/ is https://update-cardano-mainnet.iohk.io/cardano-db-sync/13/db-sync-snapshot-schema-13-block-7981218-x86_64.tgz and listed as "2 days" ago.
But block 7981218 was already minted 12 days ago on 2022/11/06 21:44:46 UTC https://explorer.cardano.org/de/block?id=9d755bf51c6e618439fcfd749656490a1ddb25950fc0ee38b37c08de0b103bb0
I just setup a new db sync server with this snapshot and it is really 12 days behind, instead of just 2 days.
Please fix the upload of current snapshots.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/93269573/202740741-5006af22-ba02-4472-a4b1-863b81775799.png">

**Comment by ArturWieczorek** [comment] 2022-11-21 11:22
@jbgi Can you please look into that ?

**Comment by pyromaniac3010** [comment] 2022-11-28 08:51
Any news on this? The newest db-sync snapshot is still https://update-cardano-mainnet.iohk.io/cardano-db-sync/13/db-sync-snapshot-schema-13-block-7981218-x86_64.tgz which is now 22 days old. That's 5 epochs already.

**Comment by kderme** [comment] 2022-12-11 15:21
I think the problem is fixed. Should we close this?

**Comment by kderme** [comment] 2023-02-17 14:31
This lookgs fixed

**Closed by kderme** 2023-02-17 14:31 UTC
Labels: bug
